/* tslint:disable */
/* eslint-disable */
/**
 * Books manager for Library
 * This is the API to get access the application to manage Bookings and Books in Library. 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { NewBookCategory } from './new-book-category';
/**
 * 
 * @export
 * @interface Book
 */
export interface book {
    /**
     * 
     * @type {number}
     * @memberof Book
     */
    idBook: number;
    /**
     * 
     * @type {string}
     * @memberof Book
     */
     title: string;
    /**
     * 
     * @type {string}
     * @memberof Book
     */
    author: string;
    /**
     * 
     * @type {number}
     * @memberof Book
     */
     pages: number;
    /**
     * 
     * @type {string}
     * @memberof Book
     */
     synopsis: string;
    /**
     * 
     * @type {NewBookCategory}
     * @memberof Book
     */
    category: NewBookCategory;
    /**
     * 
     * @type {string}
     * @memberof Book
     */
     status: string;
    /**
     * 
     * @type {number}
     * @memberof Book
     */
     numberBooking: number;
    /**
     * 
     * @type {number}
     * @memberof Book
     */
    rankBooking: number;
}
