/* tslint:disable */
/* eslint-disable */
/**
 * Books manager for Library
 * This is the API to get access the application to manage Bookings and Books in Library. 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Category
 */
export interface category {
    /**
     * 
     * @type {number}
     * @memberof Category
     */
    idCategory: number;
    /**
     * 
     * @type {string}
     * @memberof Category
     */
    nameCategory: string;
}
