/* tslint:disable */
/* eslint-disable */
/**
 * Books manager for Library
 * This is the API to get access the application to manage Bookings and Books in Library. 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { NewBookCategory } from './new-book-category';
/**
 * 
 * @export
 * @interface NewBook
 */
export interface newBook {
    /**
     * 
     * @type {string}
     * @memberof NewBook
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof NewBook
     */
    author: string;
    /**
     * 
     * @type {number}
     * @memberof NewBook
     */
    pages: number;
    /**
     * 
     * @type {string}
     * @memberof NewBook
     */
    synopsis: string;
    /**
     * 
     * @type {NewBookCategory}
     * @memberof NewBook
     */
    category: NewBookCategory;
}
