/* tslint:disable */
/* eslint-disable */
/**
 * Books manager for Library
 * This is the API to get access the application to manage Bookings and Books in Library. 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface NewUser
 */
export interface NewUser {
    /**
     * 
     * @type {string}
     * @memberof NewUser
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof NewUser
     */
    lastName?: string;
    /**
     * 
     * @type {string}
     * @memberof NewUser
     */
    username?: string;
    /**
     * 
     * @type {string}
     * @memberof NewUser
     */
    password?: string;
    /**
     * 
     * @type {string}
     * @memberof NewUser
     */
    role?: string;
}
